var options = {
  "caseSensitive": false,
  "collapseBooleanAttributes": true,
  "collapseInlineTagWhitespace": false,
  "collapseWhitespace": true,
  "conservativeCollapse": false,
  "customAttrAssign": [],
  "customAttrCollapse": /[-_\w]+/,
  "customAttrSurround": [],
  "customEventAttributes": [],
  "decodeEntities": true,
  "html5": true,
  "ignoreCustomComments": [],
  "ignoreCustomFragments": [],
  "includeAutoGeneratedTags": false,
  "keepClosingSlash": false,
  "lint": false,
  "maxLineLength": 127, // width of github code viewer
  "minifyCSS": true,
  "minifyJS": true,
  "minifyURLs": false,
  "preserveLineBreaks": false,
  "preventAttributesEscaping": false,
  "processConditionalComments": false,
  "processScripts": [
    "text/ng-template"
  ],
  "quoteCharacter": "\"",
  "removeAttributeQuotes": false,
  "removeCDATASectionsFromCDATA": false,
  "removeComments": true,
  "removeEmptyAttributes": true,
  "removeEmptyElements": false,
  "removeOptionalTags": false,
  "removeRedundantAttributes": true,
  "removeScriptTypeAttributes": true,
  "removeStyleLinkTypeAttributes": true,
  "removeTagWhitespace": false,
  "sortAttributes": false,
  "sortClassName": false,
  "useShortDoctype": false
};

module.exports = options;
